import Head from 'next/head';
import React from 'react';

interface TCHeadProps {
  title?: string;
  description?: string;
}

function TCHead({ title, description }: TCHeadProps) {
  return (
    <Head>
      <title>{title || 'Training Central'}</title>
      <meta
        name="description"
        content={description || 'Generated by create next app'}
      />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon/favicon.ico" />
    </Head>
  );
}

export default TCHead;
