import Head from 'next/head';
import React from 'react';

interface TCHeadProps {
  title?: string;
  description?: string;
}

function TCHead({ title, description }: TCHeadProps) {
  return (
    <Head>
      <title>{title || 'Training Central'}</title>
      <meta
        name="description"
        content={description || 'Generated by create next app'}
      />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon/favicon.ico" />
      {/* <link
        rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
        crossOrigin="anonymous"
      /> */}
    </Head>
  );
}

export default TCHead;
